---


# Setting the consensus

- hosts: node1
  tasks:
  - name: Setup zookeeper
    command: docker run -d --rm -it --network="my-net" --name zookeeper0 -p 2181:2181 -p 2888:2888 -p 3888:3888 -e ZOO_MY_ID=1 -e ZOO_SERVERS="server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888" hyperledger/fabric-zookeeper
    args:
      chdir: /home/ubuntu/go/src/github.com/hyperledger/fabric-demo-tdc-ansible

- hosts: node2
  tasks:
  - name: Setup zookeeper
    command: docker run -d --rm -it --network="my-net" --name zookeeper1 -p 2181:2181 -p 2888:2888 -p 3888:3888 -e ZOO_MY_ID=2 -e ZOO_SERVERS="server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888" hyperledger/fabric-zookeeper
    args:
      chdir: /home/ubuntu/go/src/github.com/hyperledger/fabric-demo-tdc-ansible
