---


- hosts: brinks
  tasks:
  # the chaincode version must be changed
  - name: install chaincode
    command: docker exec -it cli peer chaincode install -n transport1 -v {{ chaincode_version }} -l node -p /opt/gopath/src/github.com/transport
  
- hosts: protege
  tasks:
  - name: install chaincde
    command: docker exec -it cli peer chaincode install -n transport1 -v {{ chaincode_version }} -l node -p /opt/gopath/src/github.com/transport

- hosts: brinks 
  tasks:
  - name: instantiate chaincode
    command: docker exec -it cli peer chaincode instantiate -o orderer0.sempreit.com:7050 -C channel1 -n transport1 -v {{ chaincode_version }} -c '{"Args":["init"]}' -P "OR ('BrinksMSP.member','ProtegeMSP.member')"


